# Generated by Django 2.2.4 on 2019-08-25 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.Company', verbose_name='company'),
        ),
    ]
