# Generated by Django 2.2.4 on 2019-08-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointMarking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_week', models.CharField(max_length=20)),
                ('hour', models.TimeField()),
                ('type', models.CharField(choices=[('E', 'Entry'), ('IO', 'Interval Output'), ('RI', 'Return Interval'), ('L', 'Leave')], default='E', max_length=2, verbose_name='type of marking')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_marking', to='employee.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'point_marking',
                'db_table': 'point_marking',
                'ordering': ['date', 'hour', 'employee'],
            },
        ),
    ]
