# Generated by Django 2.2.4 on 2019-08-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
    ]
