# Generated by Django 2.2.4 on 2019-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100, verbose_name='cnpj')),
                ('business_name', models.CharField(max_length=300, verbose_name='business name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'company',
                'db_table': 'company',
            },
        ),
    ]
