# Generated by Django 2.2.4 on 2019-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(max_length=140, verbose_name='business name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
    ]
