# Generated by Django 2.2.4 on 2019-08-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('entry', models.TimeField(blank=True, null=True, verbose_name='entry')),
                ('interval_output', models.TimeField(blank=True, null=True, verbose_name='interval output')),
                ('return_interval', models.TimeField(blank=True, null=True, verbose_name='return interval')),
                ('leave', models.TimeField(blank=True, null=True, verbose_name='leave')),
                ('has_remunerated_rest', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='company.Company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'journey',
                'verbose_name_plural': 'journeys',
                'db_table': 'journey',
                'ordering': ['description'],
            },
        ),
    ]
