# Generated by Django 2.2.4 on 2019-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['code', 'description'], 'verbose_name': 'journey', 'verbose_name_plural': 'journeys'},
        ),
    ]
