# Generated by Django 2.2.4 on 2019-08-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_auto_20190827_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.CharField(max_length=140, verbose_name='description'),
        ),
    ]
