# Generated by Django 2.2.4 on 2019-08-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo')),
                ('descricao', models.CharField(max_length=300, verbose_name='descricao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='empresa.Empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
                'db_table': 'jornada',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='DiaTrabalhado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'SEG'), (2, 'TER'), (3, 'QUA'), (4, 'QUI'), (5, 'SEX'), (6, 'SAB'), (7, 'DOM')], default=1, verbose_name='dia')),
                ('entrada', models.TimeField(verbose_name='entrada')),
                ('entrada_intervalo', models.TimeField(blank=True, null=True, verbose_name='entrada intervalo')),
                ('saida_intervalo', models.TimeField(blank=True, null=True, verbose_name='saida intervalo')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='saida')),
                ('jornada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dia_trabalhado', to='jornadas.Jornada', verbose_name='jornada')),
            ],
            options={
                'verbose_name': 'dia trabalhado',
                'verbose_name_plural': 'dias trabalhado',
                'db_table': 'dia_trabalhado',
                'ordering': ['id'],
            },
        ),
    ]
