# Generated by Django 2.2.4 on 2019-08-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='entrada'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='entrada_intervalo',
            field=models.TimeField(blank=True, null=True, verbose_name='entrada intervalo'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='possui_dsr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='saida',
            field=models.TimeField(blank=True, null=True, verbose_name='saida'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='saida_intervalo',
            field=models.TimeField(blank=True, null=True, verbose_name='saida intervalo'),
        ),
        migrations.DeleteModel(
            name='DiaTrabalhado',
        ),
    ]
