# Generated by Django 2.2.4 on 2019-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0002_auto_20190814_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='entrada_intervalo',
        ),
        migrations.AddField(
            model_name='jornada',
            name='retorno_intervalo',
            field=models.TimeField(blank=True, null=True, verbose_name='saida intervalo'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='saida_intervalo',
            field=models.TimeField(blank=True, null=True, verbose_name='entrada intervalo'),
        ),
    ]
